export PATH="$PATH:$HOME/.config/i3/scripts"
export QT_QPA_PLATFORMTHEME="qt5ct"
export TERMINAL="urxvt"
export VISUAL="vim"
export EDITOR="vim"
export READER="zathura"
export FILE="nnn"
export BROWSER="firefox"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
