#!/bin/sh
# alias
alias aliasls="alias | grep --color=never ls"
alias aliasgrep="alias | grep --color=never grep"
alias aliasnpm="alias | grep --color=never npm"
alias aliaspacman="alias | grep --color=never pacman"
alias aliasyay="alias | grep --color=never yay"
alias aliasaur="aliasyay"
alias aliassystemd="alias | grep --color=never systemctl"
alias aliasdocker="alias | grep --color=never docker"
alias aliasyoutubedl="alias | grep --color=never youtube"

# misc
alias cp="cp -i"
alias df="df -h"
alias free="free -m"

# ls
alias ls="ls --color=auto"
alias la="ls -a"
alias ll="ls -la"

# ripgrep
alias rg="rg --color=auto"
alias grep="rg --color=auto"

# nvim
alias e="nvim"
alias vi="nvim"
alias vim="nvim"

# npm
alias nit="npm init -y"
alias ni="npm install"
alias nid="npm install -D"
alias nig="npm install -g"
alias nst="npm start"
alias nrn="npm run"
alias nls="npm ls --depth 0"

# pacman
alias pacman="pacman --color auto"
alias p="sudo pacman --noconfirm"
alias psh="pacman -Sh"
alias psi="pacman -Si"
alias psg="pacman -Sg"
alias psy="sudo pacman -Sy"
alias psu="sudo pacman -Syu"
alias pss="pacman -Ss"
alias pqh="pacman -Qh"
alias pqi="pacman -Qi"
alias pqd="pacman -Qd"
alias pqu="pacman -Qu"
alias pqs="pacman -Qs"
alias pr="sudo pacman -Rns"

#aur
alias yay="yay --aur --color=auto"
alias a="yay --noconfirm" 
alias au="yay -Syu"
alias ass="yay -Ss"

# git
alias g="git"
alias gst="git init"
alias gss="git status"
alias gct="git commit -m"
alias gps="git push"
alias gpsh="git push origin HEAD"
alias gpl="git pull"
alias gre="git remote"
alias glg="git log"
alias gck="git checkout"
alias gb="git branch"
alias gbls="git branch -a"
alias gad="git add"
alias gdf="git diff"
alias gcl="git clone"
alias grt="git reset"
alias grtl="git reset --soft HEAD~1"
alias gmr="git merge"
alias gtg="git tag"
alias gfc="git fetch"
alias grb="git rebase"

# yadm
alias y="yadm"
alias yss="yadm status"
alias yct="yadm commit -m"
alias yps="yadm push"
alias ypl="yadm pull"
alias yre="yadm remote"
alias ylg="yadm log"
alias yck="yadm checkout"
alias yad="yadm add"
alias ydf="yadm diff"
alias yrt="yadm reset"
alias yrtl="yadm reset --soft HEAD~1"
alias yrb="yadm rebase"

# systemd
alias s="sudo systemctl"
alias sst="sudo systemctl start"
alias stp="sudo systemctl stop"
alias srs="sudo systemctl restart"
alias se="sudo systemctl enable"

# docker
alias d="sudo docker"

#youtube-dl
alias yta="youtube-dl --add-metadata --extract-audio --audio-format mp3 -o '~/Music/%(artist)s/%(album)s/%(track)s.%(ext)s'"
alias ytv="youtube-dl --add-metadata -f bestvideo+bestaudio/best -o '~/Videos/%(title)s.%(ext)s'"

# rocketchat
alias drop="mongo --eval 'db.dropDatabase()'"
alias web="cd ~/Documents/web"
alias mtest="meteor npm test"
alias m="meteor"
alias mi="MONGO_URL=mongodb://localhost/initialized MONGO_OPLOG_URL=mongodb://localhost/local meteor"
alias me="MONGO_URL=mongodb://localhost/empty MONGO_OPLOG_URL=mongodb://localhost/local TEST_MODE=true meteor"
