#!/bin/sh
alias cp="cp -i"
alias g="git"
alias p="sudo pacman"
alias pss="pacman -Ss --color auto"
alias df="df -h"
alias free="free -m"
alias ls="ls --color=auto"
alias la="ls -a"
alias grep="grep --color=auto"
alias egrep="egrep --auto=color"
alias fgrep="fgrep --auto=color"
alias ccat="highlight --out-format=ansi"

# archive extractor
# usage: ex <filename>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

