#!/bin/sh

DIR=~/Pictures/Screenshots

while getopts 's' opt; do
  case "${opt}" in
    s) selection=1 ;;
  esac
done

if [ ${selection} ]
then
  maim -s -b 10000 -r blur1,blur2 -f png /dev/stdout | \
  xclip -selection clipboard -t image/png -i
else
  maim -f png | xclip -selection clipboard -t image/png -i
fi

